theme: minimal-mistakes-jekyll
minimal_mistakes_skin: "default" # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"
logo: IMG_0722.JPEG
title: Aruna Mohan
repository: "a-mohan1/a-mohan1.github.io"
author:
  name     : "Aruna Mohan"
  avatar   : "IMG_0722.JPEG"
  bio      : " "
  location : "Boston, MA"
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/a-mohan1"
 
