theme                  : "minimal-mistakes-jekyll"
remote_theme           : "mmistakes/minimal-mistakes"
minimal_mistakes_skin    : "dark" # "default" "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"

# Site Settings
locale                   : "en-US"
title                    : "Aruna Mohan"
title_separator          : "|"
name                     : "Aruna Mohan"
description              : "Portfolio."
repository               : "a-mohan1/a-mohan1" # GitHub username/repo-name e.g. "mmistakes/minimal-mistakes"
header:
  image: IMG_0722.JPEG
# Site Author
author:
  name             : "Aruna Mohan"
  avatar           : "IMG_0722.JPG" # path of avatar image, e.g. "/assets/images/bio-photo.jpg"
  bio              : "<b>Ph.D., Massachusetts Institute of Technology.</b>"            
  location         : "Boston, MA"   :  
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: https://www.github.com/a-mohan1/
    - label: "LinkedIn"
      icon: "fab fa-linkedin"
      url: "https://www.linkedin.com/in/arunamohan"
    #- label: "Resume"
    #  icon: "fas fa-file-alt"
    #  url: "/assets/misc/.pdf"



# Site Footer
footer:
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: https://www.github.com/a-mohan1/
